# Generated by Django 4.1 on 2023-11-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomC', models.CharField(max_length=80, verbose_name='Nombre de curso')),
                ('desC', models.TextField(verbose_name='Descripcion')),
                ('durC', models.DurationField(verbose_name='Duración del curso')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
