# Generated by Django 4.1 on 2023-11-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='valorC',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
