# Generated by Django 4.1 on 2023-11-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_cursos_valorc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='id',
        ),
        migrations.AddField(
            model_name='cursos',
            name='idC',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='ID Curso'),
            preserve_default=False,
        ),
    ]
