# Generated by Django 4.1 on 2023-11-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_remove_cursos_id_cursos_idc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='durC',
            field=models.CharField(max_length=80, verbose_name='Duración de curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='valorC',
            field=models.CharField(max_length=80, verbose_name='Valor de curso'),
        ),
    ]
