# Generated by Django 4.1 on 2023-11-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_cursos_durc_alter_cursos_valorc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='modC',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('Semipresencial', 'Semipresencial')], default=1, max_length=15, verbose_name='Modalidad de Curso'),
            preserve_default=False,
        ),
    ]
