# Generated by Django 4.1 on 2023-11-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_cursos_modc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='idC',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='modC',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('Semipresencial', 'Semipresencial')], max_length=15, verbose_name='Modalidad de curso'),
        ),
        migrations.CreateModel(
            name='Reviews_Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomU', models.CharField(max_length=30, verbose_name='Nombre usuario')),
                ('reviewU', models.CharField(max_length=150, verbose_name='Comentario de usuario')),
                ('fechaR', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del comentario')),
                ('cursoU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='ID curso')),
            ],
        ),
    ]
