# Generated by Django 4.1 on 2023-11-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_cursos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='image',
            field=models.ImageField(upload_to='projects'),
        ),
    ]
