# Generated by Django 4.1 on 2023-11-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_area_delete_reviews_cursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='durC',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='valorC',
        ),
        migrations.AddField(
            model_name='cursos',
            name='fechaI',
            field=models.CharField(default=1, max_length=80, verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='fechaT',
            field=models.CharField(default=1, max_length=80, verbose_name='Fecha de Termino'),
            preserve_default=False,
        ),
    ]
